name: Sync Branches

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to sync"
        required: true
        default: "odc_sample" # Default branch name to sync

env:
  GITHUB_PRIVATE_KEY_PERSONAL: ${{ secrets.PERSONAL_PVT_KEY }}
  GITHUB_PRIVATE_KEY_OFFSHORE: ${{ secrets.OFFSHORE_PVT_KEY }}

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Personal Repository
        uses: actions/checkout@v3
        with:
          repository: aravinthsridhar/dta-automation.git
          ref: ${{ github.event.inputs.branch }}
          ssh-key: ${{ env.GITHUB_PRIVATE_KEY_PERSONAL }}
          
      - name: Add Offshore Repository as Remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.GITHUB_PRIVATE_KEY_OFFSHORE }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      - name: Add Destination Repository as Remote
        run: |
          git remote add dest git@github.com:kyybatech/repo_connect_automation.git
          git fetch dest
          
      - name: Push to Destination Repository
        run: |
          git push dest  ${{ github.event.inputs.branch }}: ${{ github.event.inputs.branch }} # Replace with the branch mapping you want
