name: Sync Branches

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to sync"
        required: true
        default: "odc_sample"

env:
  GITHUB_PRIVATE_KEY_PERSONAL: ${{ secrets.PERSONAL_PVT_KEY }}
  GITHUB_PRIVATE_KEY_OFFSHORE: ${{ secrets.OFFSHORE_PVT_KEY }}
  GITHUB_PERSONAL_REPO_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
  GIHUB_PASSPAHRASE: ${{ secrets.PASSPHRASE }}

jobs:
  sync-branches:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout Personal Repository
        id: checkout-personal-repo
        uses: actions/checkout@v3
        with:
          repository: aravinthsridhar/dta-automation.git
          ref: ${{ github.event.inputs.branch }}
          token: ${{ env.GITHUB_PERSONAL_REPO_TOKEN }}

      # Step 2: Configure SSH for Offshore Repository
      - name: Add SSH Key and Configure
        id: add-ssh-key-offshore 
        run: |
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh
         echo "${{ env.GITHUB_PRIVATE_KEY_OFFSHORE }}" | tr -d '\r' > ~/.ssh/id_rsa_offshore
         chmod 600 ~/.ssh/id_rsa_offshore
         eval "$(ssh-agent -s)"
         ssh-add ~/.ssh/id_rsa_offshore
         ssh-keyscan github.com >> ~/.ssh/known_hosts
         echo "SSH authentication succeeded."

      - name: Configure Git Remote
        run: |
          git remote add dest git@github.com:kyybatech/repo_connect_automation.git
          git fetch dest || (echo "Failed to fetch from remote repository" && exit 1)
        
      # Step 3: Detect Merge Conflicts
      - name: Merge Changes
        id: merge-changes 
        run: |
          set -e
          git merge origin/${{ github.event.inputs.branch }} || (echo "Merge conflict detected!" && exit 1)

      # Step 4: Push to Destination Repository
      - name: Push to Destination Repository
        id: push-to-destination
        run: |
          set -e
          git push dest ${{ github.event.inputs.branch }}:${{ github.event.inputs.branch }} || (echo "Failed to push changes to destination" && exit 1)

      # Step 5: Debug Output (Optional)
      - name: Debug Git Status
        id: debug-git-status
        run: |
          git status
          echo "If workflow failed, debug the logs above."
